### ISSUE TITLE
Allow easier title customization

### ISSUE THREAD

**Issue by friedbunny** [mapbox/jazzy-theme#7]
We currently hardcode a [`BRANDLESS_DOCSET_TITLE`](https://github.com/mapbox/jazzy-theme/blob/681c200620233b9bf7b5b22f7a15be417324f679/templates/header.mustache#L7) title identifier that consumers of this theme are expected to replace. When https://github.com/realm/jazzy/pull/1077/ lands in a release, we should adopt that instead.

[Here’s an example of how we currently replace `BRANDLESS_DOCSET_TITLE`](https://github.com/mapbox/mapbox-gl-native/blob/b56a7181afc40029d4280d60489d989b5dddf304/platform/ios/scripts/document.sh#L50-L52), from the Maps SDK.

/cc @captainbarbosa

**Comment by 1ec5** [comment]
This theme currently needs two different titles, one branded and the other unbranded (substituting the logo for the brand name).  Neither quite matches the module name.

**Comment by 1ec5** [comment]
Fixed in #9.
